// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectivitycommons.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ObjectivityCommons module

	public static java.lang.String getCSV_DefaultColumnSeparator()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ObjectivityCommons.CSV_DefaultColumnSeparator");
	}
}