// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectivitycommonstest.proxies;

public class Child extends objectivitycommonstest.proxies.Base
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ObjectivityCommonsTest.Child";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Name("Name"),
		Category("Category"),
		Child_Parent("ObjectivityCommonsTest.Child_Parent");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Child(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ObjectivityCommonsTest.Child"));
	}

	protected Child(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject childMendixObject)
	{
		super(context, childMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("ObjectivityCommonsTest.Child", childMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ObjectivityCommonsTest.Child");
	}

	/**
	 * @deprecated Use 'Child.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static objectivitycommonstest.proxies.Child initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return objectivitycommonstest.proxies.Child.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static objectivitycommonstest.proxies.Child initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new objectivitycommonstest.proxies.Child(context, mendixObject);
	}

	public static objectivitycommonstest.proxies.Child load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return objectivitycommonstest.proxies.Child.initialize(context, mendixObject);
	}

	public static java.util.List<objectivitycommonstest.proxies.Child> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<objectivitycommonstest.proxies.Child> result = new java.util.ArrayList<objectivitycommonstest.proxies.Child>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ObjectivityCommonsTest.Child" + xpathConstraint))
			result.add(objectivitycommonstest.proxies.Child.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Child_Parent
	 */
	public final objectivitycommonstest.proxies.Parent getChild_Parent() throws com.mendix.core.CoreException
	{
		return getChild_Parent(getContext());
	}

	/**
	 * @param context
	 * @return value of Child_Parent
	 */
	public final objectivitycommonstest.proxies.Parent getChild_Parent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		objectivitycommonstest.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Child_Parent.toString());
		if (identifier != null)
			result = objectivitycommonstest.proxies.Parent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Child_Parent
	 * @param child_parent
	 */
	public final void setChild_Parent(objectivitycommonstest.proxies.Parent child_parent)
	{
		setChild_Parent(getContext(), child_parent);
	}

	/**
	 * Set value of Child_Parent
	 * @param context
	 * @param child_parent
	 */
	public final void setChild_Parent(com.mendix.systemwideinterfaces.core.IContext context, objectivitycommonstest.proxies.Parent child_parent)
	{
		if (child_parent == null)
			getMendixObject().setValue(context, MemberNames.Child_Parent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Child_Parent.toString(), child_parent.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectivitycommonstest.proxies.Child that = (objectivitycommonstest.proxies.Child) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ObjectivityCommonsTest.Child";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
