// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tagselector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TagSelector module
	public static java.util.List<tagselector.proxies.Tag> dS_GetAllTagSuggestions(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("TagSelector.DS_GetAllTagSuggestions").withParams(params).execute(context);
		java.util.List<tagselector.proxies.Tag> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(tagselector.proxies.Tag.initialize(context, obj));
		}
		return result;
	}
	public static tagselector.proxies.TagVM dS_NewTagVM(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TagSelector.DS_NewTagVM").withParams(params).execute(context);
		return result == null ? null : tagselector.proxies.TagVM.initialize(context, result);
	}
	public static java.util.List<tagselector.proxies.Tag> oCH_GetCurrentTags(IContext context, tagselector.proxies.Taggable _taggable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Taggable", _taggable == null ? null : _taggable.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("TagSelector.OCH_GetCurrentTags").withParams(params).execute(context);
		java.util.List<tagselector.proxies.Tag> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(tagselector.proxies.Tag.initialize(context, obj));
		}
		return result;
	}
	public static void oCH_RemoveAllTags(IContext context, tagselector.proxies.Taggable _taggable)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Taggable", _taggable == null ? null : _taggable.getMendixObject());
		Core.microflowCall("TagSelector.OCH_RemoveAllTags").withParams(params).execute(context);
	}
	public static void oCH_RemoveTag(IContext context, tagselector.proxies.Taggable _taggable, tagselector.proxies.TagVM _tagVM)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Taggable", _taggable == null ? null : _taggable.getMendixObject());
		params.put("TagVM", _tagVM == null ? null : _tagVM.getMendixObject());
		Core.microflowCall("TagSelector.OCH_RemoveTag").withParams(params).execute(context);
	}
	public static void oCH_SelectOrCreateTag(IContext context, tagselector.proxies.Taggable _taggable, tagselector.proxies.TagVM _tagVM)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Taggable", _taggable == null ? null : _taggable.getMendixObject());
		params.put("TagVM", _tagVM == null ? null : _tagVM.getMendixObject());
		Core.microflowCall("TagSelector.OCH_SelectOrCreateTag").withParams(params).execute(context);
	}
	public static tagselector.proxies.Tag sUB_GetOrCreateTag(IContext context, java.lang.String _tagLabel)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TagLabel", _tagLabel);
		IMendixObject result = (IMendixObject)Core.microflowCall("TagSelector.SUB_GetOrCreateTag").withParams(params).execute(context);
		return result == null ? null : tagselector.proxies.Tag.initialize(context, result);
	}
}