// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Optional;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.opencsv.CSVReader;
import csv.impl.CSV;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;

/**
 * Safer alternative for ReadNextLine from CSV module.
 * This one is more safe:
 * the original one throws an exception if the result entity has more attributes than file columns.
 * 
 * Reads a next line from a CSV - and returns an entity of the configured type.
 * This action should only be invoked from the microflow used by a ImportCSV action.
 * If the action returns an empty entity, the end of the file is reached.
 */
public class CSV_ReadNextLine_ToEntity extends CustomJavaAction<IMendixObject>
{
	private java.lang.String EntityType;
	private java.lang.Boolean SortAttributesOnMapping;
	private java.lang.String AttributesToIgnore;

	public CSV_ReadNextLine_ToEntity(IContext context, java.lang.String EntityType, java.lang.Boolean SortAttributesOnMapping, java.lang.String AttributesToIgnore)
	{
		super(context);
		this.EntityType = EntityType;
		this.SortAttributesOnMapping = SortAttributesOnMapping;
		this.AttributesToIgnore = AttributesToIgnore;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		/*
		 * Everything below is a copy from the original code - except of lines marked with //OBJ-ADDED
		 */
		ILogNode logger = CSV.getLogger();
		Object contextObj = getContext().getData().get(CSV.CONTEXT_READER_OBJ);
		if (contextObj == null || !(contextObj instanceof CSVReader)) {
			throw new CoreException("Reader not found, this action should be invoked from a Import CSV microflow.");
		}
		
		@SuppressWarnings("resource") // reader is closed by the ImportCSV action
		CSVReader reader = (CSVReader) contextObj;

		// This is implemented because declared primitives are returned in a different order than declared within the model.
		Collection<? extends IMetaPrimitive> attributes = Core.getMetaObject(this.EntityType).getDeclaredMetaPrimitives();
		List<String> attributeNames = new LinkedList<String>();
		for (IMetaPrimitive attribute : attributes) {
			String name = attribute.getName();
			if (name.equalsIgnoreCase("createdBy") || name.equalsIgnoreCase("owner") ||
				name.equalsIgnoreCase("createdDate") || name.equalsIgnoreCase("changedDate")) {
				continue;
			}
			attributeNames.add(name);
		}

		if (this.SortAttributesOnMapping) {									//OBJ-ADDED
			Collections.sort(attributeNames);
		}																	//OBJ-ADDED

		String line[] = reader.readNext();
		if (line == null) {
			logger.debug("End of file has been reached.");
			return null;
		}

		//OBJ-ADDED
		List<String> ignoreAttribs = Arrays.asList(
			Optional
			.ofNullable(this.AttributesToIgnore)
			.orElse("")
			.split(",")
		);

		IMendixObject result = Core.instantiate(getContext(), this.EntityType);
		int counter = 0;
		for (String attributeName : attributeNames) {
			if (counter == line.length) break;								//OBJ-ADDED
			if (ignoreAttribs.contains(attributeName)) continue;			//OBJ-ADDED
			result.setValue(getContext(), attributeName, line[counter]);
			counter++;
		}
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CSV_ReadNextLine_ToEntity";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
