// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import objectivitycommons.proxies.KeyValue;
import objectivitycommons.proxies.KeyValueContainer;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;

/**
 * Generates a list of KeyValueContainer objects from input JSON array. Each array element is represented as a single KeyValueContainer object with associated collection of KeyValue objects. Each KeyValue object represents a single attribute (key/value pair) of its parent object. Additionally, the KeyValueContainer objects hold a single attribute ('id' recommended for most use cases) for easier identification. The attribute will be duplicated in the associated KeyValue object.
 * 
 * Input: 
 *      JSON array (string)
 *      Key for container value (string)
 * 
 * Output: 
 *      List of KeyValueContainer objects.
 *      KeyValueContainer:
 *            - Key    - provided key for container value
 *            - Value - value of the key attribute for given object
 *            - Index - order number (0-indexed)
 *     Associations:
 *            - ParentChildren - collection of the attributes as KeyValue objects.
 *               KeyValue:
 *                    - Key    - key of the attribute
 *                    - Value - value of the attribute
 *                    - Index - order number (0-indexed) within a single container
 * 
 * Example:
 *      For JSON: [{"id":1, "name": "name1"},{"id":2, "name": "name2"}]
 * 
 *      Results (indexed by array row index):
 *      Result for keyForContainerValue = "id": [
 *           {Value: "1", Index: 0, ParentChildren:  [{Key: "id", Value: "1"}, {Key: "name", Value: "name1"}] },
 *           {Value: "2", Index: 1, ParentChildren:  [{Key: "id", Value: "2"}, {Key: "name", Value: "name2"}] }
 *      ]
 * 
 */
public class JSON_Array_GetKeyValuePairs extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String JSON;
	private java.lang.String keyForContainerValue;

	public JSON_Array_GetKeyValuePairs(IContext context, java.lang.String JSON, java.lang.String keyForContainerValue)
	{
		super(context);
		this.JSON = JSON;
		this.keyForContainerValue = keyForContainerValue;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
	    List<IMendixObject> result = new ArrayList<IMendixObject>();
	    IContext ctx = this.getContext();
		boolean setContainerValue = keyForContainerValue != null && !keyForContainerValue.isBlank();

		JSONArray json = new JSONArray(JSON);
		for (int idxRows = 0 ; idxRows < json.length(); idxRows++) {
		    JSONObject obj = json.getJSONObject(idxRows);

			KeyValueContainer dtoContainer = new KeyValueContainer(ctx);
			dtoContainer.setIndex(idxRows);

			if (setContainerValue) {
				var containerValue = obj.optString(keyForContainerValue);
				dtoContainer.setValue(containerValue);
			}

			String[] names = JSONObject.getNames(obj);
			for (int idxNames = 0 ; idxNames < names.length; idxNames++) {
				var key = names[idxNames];
				var value = obj.optString(key);
				KeyValue dto = new KeyValue(ctx);
				dto.setKey(key);
				dto.setValue(value);
				dto.setIndex(idxNames);
				dto.setParentChildren(dtoContainer);
			}

			result.add(dtoContainer.getMendixObject());
		}

		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JSON_Array_GetKeyValuePairs";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
