// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import objectivitycommons.proxies.StringValue;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;

/**
 * Generates a list of KeyValue objects from input JSON array. Each array element is represented as a single chosen attribute (key/value pair) mapped to Mendix objects indexed with an order number. 
 * 
 * Input: 
 *      JSON array (string)
 *      Key of the attribute (string)
 * 
 * Output: 
 *      List of KeyValue objects.
 *      Attributes:
 *            - Key    - provided key
 *            - Value - value for given object
 *            - Index - order number (0-indexed)
 * 
 * Example:
 *      For JSON: [{"id":1, "name": "name1"},{"id":2, "name": "name2"}]
 * 
 *      Results (indexed by array row index):
 *      Result for key = "id": [{Value: "1", Index": 0}, {Value: "2", Index": 1}]
 *      Result for key = "name": [{Value: "name1", Index": 0}, {Value: "name2", Index": 1}]
 */
public class JSON_Array_GetByKey extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String JSON;
	private java.lang.String key;

	public JSON_Array_GetByKey(IContext context, java.lang.String JSON, java.lang.String key)
	{
		super(context);
		this.JSON = JSON;
		this.key = key;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
	    List<IMendixObject> result = new ArrayList<IMendixObject>();
	    IContext ctx = this.getContext();

		JSONArray json = new JSONArray(JSON);
		for (int idxRows = 0 ; idxRows < json.length(); idxRows++) {
		    JSONObject obj = json.getJSONObject(idxRows);
			var value = obj.optString(key);
			StringValue dto = new StringValue(ctx);
		    dto.setValue(value);
		    dto.setIndex(idxRows);
		    result.add(dto.getMendixObject());
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JSON_Array_GetByKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
