// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Returns a string containing extracted value from provided JSON object.
 * 
 * Input: 
 *      JSON object (string)
 *      Key of the attribute (string)
 * 
 * Output: 
 *      Extracted value as a string (string)
 * 
 * Example:
 *      For JSON: {"id":1, "name": "name1"}
 * 
 *      Result for key = "id": "1"
 *      Result for key = "name": "name1"
 */
public class JSON_Object_GetByKey extends CustomJavaAction<java.lang.String>
{
	private java.lang.String JSON;
	private java.lang.String key;

	public JSON_Object_GetByKey(IContext context, java.lang.String JSON, java.lang.String key)
	{
		super(context);
		this.JSON = JSON;
		this.key = key;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		JSONObject obj = new JSONObject(JSON);
		var value = obj.optString(key);
		return value;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JSON_Object_GetByKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
