// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns copy of Input list with distinct values (for the given Attribute): duplicates are ignored.
 * Example:
 * Input: 1,2,3,2,1,,,end
 * Output: 1,2,3,,end
 */
public class ListDistinct extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> List;
	private java.lang.String Attribute;

	public ListDistinct(IContext context, java.util.List<IMendixObject> List, java.lang.String Attribute)
	{
		super(context);
		this.List = List;
		this.Attribute = Attribute;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		String atr = Optional.ofNullable(this.Attribute).orElse("").trim();
		if (atr.isEmpty()) throw new MendixRuntimeException("Attribute cannot be empty");

		IContext ctx = this.getContext();	
		List<Object> distVals = new ArrayList<Object>();
		List<IMendixObject> distMxObjs = new ArrayList<IMendixObject>();

		for (IMendixObject mxObj : List) {
			Object val = mxObj.getValue(ctx, atr);
			if (!distVals.contains(val)) {
				distVals.add(val);
				distMxObjs.add(mxObj);
			}
		}

		return distMxObjs;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListDistinct";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
