// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns a sublist of a given list. Elements from start index (offset) to the end index (amount + offset) are taken.
 * 
 * If offset is not given, then default value is assumed - 0.
 * If the end index exceeds the bounds of the list, then all remaining elements are returned.
 * 
 * Example:
 * Input: 
 *      list: [3,6,2,5,7], offset: 1, amount: 3
 * Output: 
 *       [6,2,5]
 */
public class ListTake extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> list;
	private java.lang.Long offset;
	private java.lang.Long amount;

	public ListTake(IContext context, java.util.List<IMendixObject> list, java.lang.Long offset, java.lang.Long amount)
	{
		super(context);
		this.list = list;
		this.offset = offset;
		this.amount = amount;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		int fromIndex = offset == null ? 0 : offset.intValue();
		int toIndex = amount == null ? fromIndex : fromIndex + amount.intValue();
		
		int listLength = list.size();
		
		if (toIndex > listLength) toIndex = listLength;
		if (fromIndex > toIndex) fromIndex = toIndex;
		
		return list.isEmpty() ? list : list.subList(fromIndex, toIndex);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListTake";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
