// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * See:
 * JamCommons: ArrayGet
 * Java: List.get
 * JavaScript: Array[]
 * 
 * Returns list item by the given index, zero-based.
 * In case of non-existing index returns empty.
 */
public class ListGetByIndex extends CustomJavaAction<IMendixObject>
{
	private java.util.List<IMendixObject> List;
	private java.lang.Long Index;

	public ListGetByIndex(IContext context, java.util.List<IMendixObject> List, java.lang.Long Index)
	{
		super(context);
		this.List = List;
		this.Index = Index;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return (this.Index >= this.List.size() || this.Index < 0)
			? null
			: this.List.get(this.Index.intValue());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListGetByIndex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
