// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import javax.websocket.OnError;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Returns substring between OpeningTag and ClosingTag - or empty if >= 1 of tags is missing
 */
public class StringBetween extends CustomJavaAction<java.lang.String>
{
	private java.lang.String String;
	private java.lang.String OpeningTag;
	private java.lang.String ClosingTag;

	public StringBetween(IContext context, java.lang.String String, java.lang.String OpeningTag, java.lang.String ClosingTag)
	{
		super(context);
		this.String = String;
		this.OpeningTag = OpeningTag;
		this.ClosingTag = ClosingTag;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String s = this.String;
		if (s == null || s.isEmpty()) return "";

		int beg = s.indexOf(OpeningTag);
		if (beg == -1) return "";

		s = s.substring(beg + OpeningTag.length());

		int end = s.indexOf(ClosingTag);
		if (end == -1) return "";

		s = s.substring(0, end);
		return s;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringBetween";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
