// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Full implementation of Java String.replaceAll()
 * 
 * Stronger then Mendix replaceAll/First() string functions: the replacement patterns are supported.
 * 
 * See:
 * https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll(java.lang.String,%20java.lang.String)
 * 
 * https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#cg
 * 
 */
public class StringReplaceRegex extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Input;
	private java.lang.String Regex;
	private java.lang.String ReplacePattern;

	public StringReplaceRegex(IContext context, java.lang.String Input, java.lang.String Regex, java.lang.String ReplacePattern)
	{
		super(context);
		this.Input = Input;
		this.Regex = Regex;
		this.ReplacePattern = ReplacePattern;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Pattern pattern = Pattern.compile(Regex);
		Matcher matcher = pattern.matcher(Input);
		return matcher.replaceAll(ReplacePattern);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringReplaceRegex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
