// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import objectivitycommons.proxies.ValueVM;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * See:
 * CommunityCommons: StringSplit
 * JamCommons: StringSplit
 * Java: String.split
 * JavaScript: String.split
 * 
 * The splitting result is returned as list of ValueVM with String = value and Integer = index.
 */
public class StringSplit extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String String;
	private java.lang.String Separator;

	public StringSplit(IContext context, java.lang.String String, java.lang.String Separator)
	{
		super(context);
		this.String = String;
		this.Separator = Separator;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		String str = Optional.ofNullable(this.String).orElse("");
		String sep = Optional.ofNullable(this.Separator).orElse("");
		IContext ctx = this.getContext();
		List<IMendixObject> result = new ArrayList<IMendixObject>();
		int idx = 0;
		for (String part : str.split(sep)) {
			ValueVM vm = new ValueVM(ctx);
			vm.setString(part);
			vm.setInteger(idx++);
			result.add(vm.getMendixObject());
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringSplit";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
