// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectivitycommons.actions;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Mendix wrapper for Java for URLEncoder.encode method. Encodes in UTF-8 format.
 * 
 * See: https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html
 */
public class URLEncode extends CustomJavaAction<java.lang.String>
{
	private java.lang.String InputString;

	public URLEncode(IContext context, java.lang.String InputString)
	{
		super(context);
		this.InputString = InputString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (InputString == null) {
			return null;
		} else {
			return URLEncoder.encode(InputString, StandardCharsets.UTF_8);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "URLEncode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
