// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package signinmicroflow.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the SignInMicroflow module
	public static boolean aSU(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("SignInMicroflow.ASU").withParams(params).execute(context);
	}
	public static void signIn_After(IContext context, system.proxies.User _anoUser, system.proxies.User _signInUser, java.lang.String _password)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AnoUser", _anoUser == null ? null : _anoUser.getMendixObject());
		params.put("SignInUser", _signInUser == null ? null : _signInUser.getMendixObject());
		params.put("Password", _password);
		Core.microflowCall("SignInMicroflow.SignIn_After").withParams(params).execute(context);
	}
	public static boolean signIn_Before(IContext context, java.lang.String _userName, java.lang.String _password)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserName", _userName);
		params.put("Password", _password);
		return (java.lang.Boolean) Core.microflowCall("SignInMicroflow.SignIn_Before").withParams(params).execute(context);
	}
}
