// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This action retrieves current user session.
 * @returns {Promise.<MxObject>}
 */
export async function CurrentSession_JS() {
	// BEGIN USER CODE
	return new Promise((resolve, reject) => {
		try {
			let sessionID = mx.session.getSessionObjectId();
			mx.data.get({
                    guid: sessionID,
                    callback: function (objs) {
                        resolve(objs);
                    },
                });
		} catch (e) {
			reject(e);
		}
	});
	// END USER CODE
}
