// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This action checks whether current page name equals provided value.
 * 
 * Input: page name (string)
 * Output: true if current page name equals input (boolean)
 * 
 * Note: 
 * Does not work for popups and modals.
 * 
 * Page format example: ObjectivityCommons.WidgetExport.page.xml
 * @param {string} pageName
 * @returns {Promise.<boolean>}
 */
export async function CurrentPageEquals_JS(pageName) {
	// BEGIN USER CODE
	let contentForm = mx.ui.getContentForm();
	if(!contentForm || contentForm.path !== pageName){
		return false;
	}
	else
		return true;
	// END USER CODE
}
