// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Returns currentUser object cast to User entity without performing server call.
 * @param {string} userEntity - Type of the current user entity to be returned by the action.
 * @returns {Promise.<MxObject>}
 */
export async function CurrentUserObject_JS(userEntity) {
	// BEGIN USER CODE
	return new Promise((resolve, reject) => {
		try {
			let userObject = mx.session.getUserObject();
			if (!mx.session || !userObject ||
				userObject.getEntity() !== userEntity) {
				resolve(); // return empty
				return;
			}
			resolve(userObject);
		} catch (e) {
			reject(e);
		}
	});
	// END USER CODE
}
