// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * This action checks whether current user has role with provided role name.
 * 
 * Input: role name (string)
 * Output: true if role is assigned (boolean)
 * @param {string} role
 * @returns {Promise.<boolean>}
 */
export async function HasUserRole_JS(role) {
	// BEGIN USER CODE
	return new Promise((resolve, reject) => {
		try {
			let userRoleArray = mx.session.getUserRoleNames();
			let found = userRoleArray.includes(role);
			resolve(found);
		} catch (e) {
			reject(e);
		}
	});
	// END USER CODE
}
