// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { getSource } from "./Grid_SelectionHelper.js"

// BEGIN EXTRA CODE


// END EXTRA CODE

/**
 * This action returns `size` number of objects from `grid` that are being listed.
 * @param {string} gridName - DOM selector of data grid e.g. mx-name-datagrid0
 * @param {string} outputEntity - Type of returned object list
 * @param {Big} size - Number of objects to return. Set -1 for all
 * @returns {Promise.<MxObject[]>}
 */
export async function JS_DataGrid_GetObjects(gridName, outputEntity, size) {
	// BEGIN USER CODE
    let node = document.querySelector("." + gridName);
    let grid = dijit.registry.byNode(node);
    let selectedMxObjects = await getSource(grid, size);
    return selectedMxObjects;
	// END USER CODE
}
