// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { serializeMxObject, stringify } from "./_helpers"

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * See JavaScript: JSON.stringify
 * @param {MxObject[]} list - Input list of objects
 * @param {Big} space - Number of space characters to use as white space for indenting: 0 - 10; default = 2.
 * @returns {Promise.<string>}
 */
export async function JsonStringifyList_JS(list, space) {
	// BEGIN USER CODE
	let arr = list.map(obj => serializeMxObject(obj));
	let ret = stringify(arr, space);
	return Promise.resolve(ret);
	// END USER CODE
}
