// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Removes class from elements with given selector.
 * @param {string} selector - CSS selector to find desired elements
 * @param {string} classToRemove - Class name to remove
 * @returns {Promise.<void>}
 */
export async function RemoveClassFromElements_JS(selector, classToRemove) {
	// BEGIN USER CODE
	document.querySelectorAll(selector).forEach(element => {
		element.classList.remove(classToRemove);
	});

	// END USER CODE
}
