// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Sets current caret position in the edited text.
 * @param {Big} caretPosition - Caret position to set
 * @returns {Promise.<void>}
 */
export async function SetCaretPosition_JS(caretPosition) {
	// BEGIN USER CODE
	var input = document.querySelector('.mx-input-stayfocused').children.item(0);
	input.focus()
	input.selectionEnd = caretPosition;
	// END USER CODE
}
