// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Sets innerHTML attribute of HTML element.
 * @param {string} text - Replacement text
 * @param {string} selector - CSS selector to find desired element
 * @returns {Promise.<void>}
 */
export async function SetInnerHTML_JS(text, selector) {
	// BEGIN USER CODE
	document.querySelector(selector).innerHTML = text;
	// END USER CODE
}
