// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Counts number of occurences of Separator in the given input String
 * @param {string} string - Input string to count occurences of Separator
 * @param {string} separator
 * @returns {Promise.<Big>}
 */
export async function StringCount_JS(string, separator) {
	// BEGIN USER CODE
	let str = string || '';
	let sep = separator || '';
	let parts = str.split(sep);
	return Promise.resolve(parts.length - 1);
	// END USER CODE
}
