// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Full implementation of JS String.replace()
 * 
 * Stronger then Mendix replaceAll/First() string functions: the replacement patterns are supported.
 * 
 * See:
 * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter
 * @param {string} input
 * @param {string} regex
 * @param {string} regexFlags
 * @param {string} replacePattern - Supports $ paterns (e.g. '$n' => the nth parenthesized submatch string).
See documentation for details.
 * @returns {Promise.<string>}
 */
export async function StringReplaceRegex_JS(input, regex, regexFlags, replacePattern) {
	// BEGIN USER CODE
	let inputRegex = new RegExp(regex, regexFlags);
	let result = (input||'').replace(inputRegex, replacePattern);
	return Promise.resolve(result);
	// END USER CODE
}
