// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Opens the provided URL in the web browser.
 * @param {string} url - This field is required.
 * @param {boolean} inNewTab
 * @returns {Promise.<boolean>}
 */
export async function UrlOpen_JS(url, inNewTab) {
	// BEGIN USER CODE
    if (!url) {
        return Promise.reject(new Error("Input parameter 'Url' is required"));
    }
    if (window) {
        if (inNewTab) {
            window.open(url, '_blank').focus();
        } else {
            window.location = url;
        }
        return Promise.resolve(true);
    }
    return Promise.resolve(false);
	// END USER CODE
}
