// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package _test.proxies;

public class Child extends _test.proxies.Base
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "_Test.Child";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Name("Name"),
		Category("Category"),
		Child_Parent("_Test.Child_Parent"),
		Taggable_Tag("TagSelector.Taggable_Tag");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Child(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Child(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject childMendixObject)
	{
		super(context, childMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, childMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Child.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static _test.proxies.Child initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return _test.proxies.Child.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static _test.proxies.Child initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new _test.proxies.Child(context, mendixObject);
	}

	public static _test.proxies.Child load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return _test.proxies.Child.initialize(context, mendixObject);
	}

	public static java.util.List<_test.proxies.Child> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> _test.proxies.Child.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Child_Parent
	 */
	public final _test.proxies.Parent getChild_Parent() throws com.mendix.core.CoreException
	{
		return getChild_Parent(getContext());
	}

	/**
	 * @param context
	 * @return value of Child_Parent
	 * @throws com.mendix.core.CoreException
	 */
	public final _test.proxies.Parent getChild_Parent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		_test.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Child_Parent.toString());
		if (identifier != null) {
			result = _test.proxies.Parent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Child_Parent
	 * @param child_parent
	 */
	public final void setChild_Parent(_test.proxies.Parent child_parent)
	{
		setChild_Parent(getContext(), child_parent);
	}

	/**
	 * Set value of Child_Parent
	 * @param context
	 * @param child_parent
	 */
	public final void setChild_Parent(com.mendix.systemwideinterfaces.core.IContext context, _test.proxies.Parent child_parent)
	{
		if (child_parent == null) {
			getMendixObject().setValue(context, MemberNames.Child_Parent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Child_Parent.toString(), child_parent.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final _test.proxies.Child that = (_test.proxies.Child) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
