// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package _test.proxies;

public class TestContextVM
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testContextVMMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "_Test.TestContextVM";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Text("Text"),
		Bool("Bool"),
		Separator("Separator"),
		Url("Url"),
		OpeningTag("OpeningTag"),
		ClosingTag("ClosingTag"),
		Csv_Text("Csv_Text"),
		Csv_ColumnHeader("Csv_ColumnHeader"),
		Csv_ColumnSeparator("Csv_ColumnSeparator"),
		Csv_RowIndex("Csv_RowIndex"),
		TestContextVM_User("_Test.TestContextVM_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestContextVM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "_Test.TestContextVM"));
	}

	protected TestContextVM(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testContextVMMendixObject)
	{
		if (testContextVMMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("_Test.TestContextVM", testContextVMMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a _Test.TestContextVM");

		this.testContextVMMendixObject = testContextVMMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestContextVM.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static _test.proxies.TestContextVM initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return _test.proxies.TestContextVM.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static _test.proxies.TestContextVM initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new _test.proxies.TestContextVM(context, mendixObject);
	}

	public static _test.proxies.TestContextVM load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return _test.proxies.TestContextVM.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Bool
	 */
	public final java.lang.Boolean getBool()
	{
		return getBool(getContext());
	}

	/**
	 * @param context
	 * @return value of Bool
	 */
	public final java.lang.Boolean getBool(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Bool.toString());
	}

	/**
	 * Set value of Bool
	 * @param bool
	 */
	public final void setBool(java.lang.Boolean bool)
	{
		setBool(getContext(), bool);
	}

	/**
	 * Set value of Bool
	 * @param context
	 * @param bool
	 */
	public final void setBool(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean bool)
	{
		getMendixObject().setValue(context, MemberNames.Bool.toString(), bool);
	}

	/**
	 * @return value of Separator
	 */
	public final java.lang.String getSeparator()
	{
		return getSeparator(getContext());
	}

	/**
	 * @param context
	 * @return value of Separator
	 */
	public final java.lang.String getSeparator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Separator.toString());
	}

	/**
	 * Set value of Separator
	 * @param separator
	 */
	public final void setSeparator(java.lang.String separator)
	{
		setSeparator(getContext(), separator);
	}

	/**
	 * Set value of Separator
	 * @param context
	 * @param separator
	 */
	public final void setSeparator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String separator)
	{
		getMendixObject().setValue(context, MemberNames.Separator.toString(), separator);
	}

	/**
	 * @return value of Url
	 */
	public final java.lang.String getUrl()
	{
		return getUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of Url
	 */
	public final java.lang.String getUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Url.toString());
	}

	/**
	 * Set value of Url
	 * @param url
	 */
	public final void setUrl(java.lang.String url)
	{
		setUrl(getContext(), url);
	}

	/**
	 * Set value of Url
	 * @param context
	 * @param url
	 */
	public final void setUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.Url.toString(), url);
	}

	/**
	 * @return value of OpeningTag
	 */
	public final java.lang.String getOpeningTag()
	{
		return getOpeningTag(getContext());
	}

	/**
	 * @param context
	 * @return value of OpeningTag
	 */
	public final java.lang.String getOpeningTag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OpeningTag.toString());
	}

	/**
	 * Set value of OpeningTag
	 * @param openingtag
	 */
	public final void setOpeningTag(java.lang.String openingtag)
	{
		setOpeningTag(getContext(), openingtag);
	}

	/**
	 * Set value of OpeningTag
	 * @param context
	 * @param openingtag
	 */
	public final void setOpeningTag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String openingtag)
	{
		getMendixObject().setValue(context, MemberNames.OpeningTag.toString(), openingtag);
	}

	/**
	 * @return value of ClosingTag
	 */
	public final java.lang.String getClosingTag()
	{
		return getClosingTag(getContext());
	}

	/**
	 * @param context
	 * @return value of ClosingTag
	 */
	public final java.lang.String getClosingTag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClosingTag.toString());
	}

	/**
	 * Set value of ClosingTag
	 * @param closingtag
	 */
	public final void setClosingTag(java.lang.String closingtag)
	{
		setClosingTag(getContext(), closingtag);
	}

	/**
	 * Set value of ClosingTag
	 * @param context
	 * @param closingtag
	 */
	public final void setClosingTag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String closingtag)
	{
		getMendixObject().setValue(context, MemberNames.ClosingTag.toString(), closingtag);
	}

	/**
	 * @return value of Csv_Text
	 */
	public final java.lang.String getCsv_Text()
	{
		return getCsv_Text(getContext());
	}

	/**
	 * @param context
	 * @return value of Csv_Text
	 */
	public final java.lang.String getCsv_Text(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Csv_Text.toString());
	}

	/**
	 * Set value of Csv_Text
	 * @param csv_text
	 */
	public final void setCsv_Text(java.lang.String csv_text)
	{
		setCsv_Text(getContext(), csv_text);
	}

	/**
	 * Set value of Csv_Text
	 * @param context
	 * @param csv_text
	 */
	public final void setCsv_Text(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csv_text)
	{
		getMendixObject().setValue(context, MemberNames.Csv_Text.toString(), csv_text);
	}

	/**
	 * @return value of Csv_ColumnHeader
	 */
	public final java.lang.String getCsv_ColumnHeader()
	{
		return getCsv_ColumnHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of Csv_ColumnHeader
	 */
	public final java.lang.String getCsv_ColumnHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Csv_ColumnHeader.toString());
	}

	/**
	 * Set value of Csv_ColumnHeader
	 * @param csv_columnheader
	 */
	public final void setCsv_ColumnHeader(java.lang.String csv_columnheader)
	{
		setCsv_ColumnHeader(getContext(), csv_columnheader);
	}

	/**
	 * Set value of Csv_ColumnHeader
	 * @param context
	 * @param csv_columnheader
	 */
	public final void setCsv_ColumnHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csv_columnheader)
	{
		getMendixObject().setValue(context, MemberNames.Csv_ColumnHeader.toString(), csv_columnheader);
	}

	/**
	 * @return value of Csv_ColumnSeparator
	 */
	public final java.lang.String getCsv_ColumnSeparator()
	{
		return getCsv_ColumnSeparator(getContext());
	}

	/**
	 * @param context
	 * @return value of Csv_ColumnSeparator
	 */
	public final java.lang.String getCsv_ColumnSeparator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Csv_ColumnSeparator.toString());
	}

	/**
	 * Set value of Csv_ColumnSeparator
	 * @param csv_columnseparator
	 */
	public final void setCsv_ColumnSeparator(java.lang.String csv_columnseparator)
	{
		setCsv_ColumnSeparator(getContext(), csv_columnseparator);
	}

	/**
	 * Set value of Csv_ColumnSeparator
	 * @param context
	 * @param csv_columnseparator
	 */
	public final void setCsv_ColumnSeparator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csv_columnseparator)
	{
		getMendixObject().setValue(context, MemberNames.Csv_ColumnSeparator.toString(), csv_columnseparator);
	}

	/**
	 * @return value of Csv_RowIndex
	 */
	public final java.lang.Integer getCsv_RowIndex()
	{
		return getCsv_RowIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of Csv_RowIndex
	 */
	public final java.lang.Integer getCsv_RowIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Csv_RowIndex.toString());
	}

	/**
	 * Set value of Csv_RowIndex
	 * @param csv_rowindex
	 */
	public final void setCsv_RowIndex(java.lang.Integer csv_rowindex)
	{
		setCsv_RowIndex(getContext(), csv_rowindex);
	}

	/**
	 * Set value of Csv_RowIndex
	 * @param context
	 * @param csv_rowindex
	 */
	public final void setCsv_RowIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer csv_rowindex)
	{
		getMendixObject().setValue(context, MemberNames.Csv_RowIndex.toString(), csv_rowindex);
	}

	/**
	 * @return value of TestContextVM_User
	 */
	public final system.proxies.User getTestContextVM_User() throws com.mendix.core.CoreException
	{
		return getTestContextVM_User(getContext());
	}

	/**
	 * @param context
	 * @return value of TestContextVM_User
	 */
	public final system.proxies.User getTestContextVM_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestContextVM_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestContextVM_User
	 * @param testcontextvm_user
	 */
	public final void setTestContextVM_User(system.proxies.User testcontextvm_user)
	{
		setTestContextVM_User(getContext(), testcontextvm_user);
	}

	/**
	 * Set value of TestContextVM_User
	 * @param context
	 * @param testcontextvm_user
	 */
	public final void setTestContextVM_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User testcontextvm_user)
	{
		if (testcontextvm_user == null)
			getMendixObject().setValue(context, MemberNames.TestContextVM_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestContextVM_User.toString(), testcontextvm_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testContextVMMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final _test.proxies.TestContextVM that = (_test.proxies.TestContextVM) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "_Test.TestContextVM";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
